accounts/urls.py
from django.conf import settings
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.conf.urls import url
from django.conf.urls.static import static
from django.urls import path
from . import views

urlpatterns = [
    url(r'^$', views.index, name="login_register"),
    url(r'^register$', views.register, name="register"),
    url(r'^login/$', views.login, name="login"),
    url(r'^logout/$', views.logout, name="logout"),
    url(r'^reset_password/$', PasswordResetView.as_view(template_name="accounts/password_reset.html"), name="password_reset"),
    url(r'^reset_password_sent/$', PasswordResetDoneView.as_view(template_name="accounts/password_reset_sent.html"), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name="accounts/password_reset_form.html"), name="password_reset_confirm"),
    url(r'^reset_password_complete/$', PasswordResetCompleteView.as_view(template_name="accounts/password_reset_done.html"), name="password_reset_complete"),
    path('area', views.area_handle, name="area"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

basiclivings/urls.py
from django.conf.urls import url
from django.conf.urls.static import static

from . import views, settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    url(r'^$', views.index, name="main_home"),
    path('logout/', views.logout, name="LoggedOut"),
    url(r'^update_user/$', views.update_user, name="update_user"),
    url(r'^change-password', views.change_password, name='change_password'),
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),
    path('payingGuest/', include('payingGuest.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static

from django.urls import path
from . import views

urlpatterns = [
    url(r'^$', views.index, name="food_index"),
    url(r'^details/(?P<id>\d+)/$', views.details, name="DetailPage"),
    url(r'^vendor/$', views.vendor_index, name="food_vendor_index"),
    url(r'^vendor/addmess/$', views.addmess, name="add_mess"),
    path('area', views.area_handle, name="area"),
    path('filter', views.filterdata, name="filter"),
    path('vendor/addmess/area', views.area_handle, name="area_vendor"),
    url(r'^vendor/addmess/submitMess/$', views.submitMess, name="submit_mess"),
    url(r'^vendor/viewmess/$', views.viewmess, name="view_mess"),
    url(r'^vendor/viewfoodtype/$', views.viewfoodtype, name="view_food_types"),
    url(r'^vendor/managestudent/$', views.managestudent, name="food_manage_student"),
    path('vendor/managestudent/delete', views.delete, name="delete_student"),
    url(r'^vendor/payment/$', views.payment, name="payment_food"),
    url(r'^vendor/payment/handlerequest/$', views.handlerequest, name="handle_request_food"),
    url(r'^vendor/managepayment/(?P<rid>\d+)/$', views.managepayment, name="managepayment_food"),
    url(r'^vendor/manageEmail/$', views.manageEmail, name="food_manage_email"),
    path('vendor/manageEmail/send-mail', views.sendEmail, name="food_send_email"),
    url(r'^vendor/addfoodtype/$', views.addfoodtype, name="add_food_type"),
    url(r'^vendor/addfoodtype/submit/$', views.submitType, name="submit_food_type"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.core.mail import send_mail
from datetime import datetime
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.translation import ugettext_lazy as _
from .managers import UserManager
from django.core.validators import RegexValidator
# Create your models here.


class PublicQueries(models.Model):
    query_id = models.AutoField(primary_key=True)
    sender = models.CharField(max_length=30, null=False)
    email = models.EmailField(max_length=300, null=False)
    subject = models.CharField(max_length=50)
    date_posted = models.DateTimeField(default=datetime.today())
    message = models.CharField(max_length=1024, null=False, blank=False)

    class Meta:
        db_table = "public_queries"
        verbose_name = "Public Query"
        verbose_name_plural = "Public Queries"

    def __str__(self):
        return self.sender


class Packages(models.Model):
    package_id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200, null=True)
    description = models.CharField(max_length=300, null=False)
    duration = models.PositiveIntegerField(null=False, blank=False)
    price = models.PositiveIntegerField(null=False, blank=False)
    is_active = models.BooleanField(default=True)

    class Meta:
        db_table = "packages"
        verbose_name = "Packages"
        verbose_name_plural = "Packages"
        
    def __str__(self):
        return self.title


class City(models.Model):
    city_id = models.AutoField(primary_key=True)
    city_name = models.CharField(max_length=30, unique=True)

    class Meta:
        db_table = 'city'
        verbose_name = "City"
        verbose_name_plural = "Cities"

    def __str__(self):
        return str(self.city_name)

    def get_city_name(self):
        return str(self.city_name)


class Area(models.Model):
    area_id = models.AutoField(primary_key=True)
    area_name = models.CharField(max_length=40)
    city_id = models.ForeignKey(City, on_delete=models.CASCADE, db_column='city_id')
    pincode = models.CharField(max_length=6, default="")

    class Meta:
        db_table = 'Area'
        verbose_name = "Area"
        verbose_name_plural = "Areas"

    def __str__(self):
        return self.area_name
    
    def get_area_name(self):
        return self.area_name
    
    @property
    def city(self):
        return self.city_id.city_name


class User(AbstractBaseUser, PermissionsMixin):
    GENDER_LIST = (
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Others', 'Others')
    )
    username = None
    RegexValid = RegexValidator(regex=r'^(\+91[\-\s]?)?[0]?(91)?[789]\d{9}$', message="Enter valid Phone Number", code="Invalid Phone Number")
    user_id = models.AutoField(primary_key=True)
    first_name = models.CharField(_('first name'), max_length=30, unique=False, blank=False, null=False)
    last_name = models.CharField(_('last name'), max_length=30, unique=False, blank=True, null=True)
    email = models.EmailField(_('email'), unique=True, null=False, blank=False)
    gender = models.CharField(_('gender'), choices=GENDER_LIST, blank=False, max_length=10, null=False)
    address = models.CharField(_('address'), blank=False, null=False, max_length=200, default="")
    phone = models.CharField(_('phone'), validators=[RegexValid],max_length=10, blank=False, null=False, default="")
    is_pgVendor = models.BooleanField(_('pgVendor'), default=False, blank=False, null=False)
    is_foodVendor = models.BooleanField(_('foodVendor'), default=False, blank=False, null=False)
    is_student = models.BooleanField(_('student'), default=True, blank=False, null=False)
    area_id = models.ForeignKey(Area, on_delete=models.CASCADE, db_column='area_id', blank=True, null=True)
    date_joined = models.DateTimeField(_('date joined'), default=datetime.today())
    email_verified_at = models.DateTimeField(_('email verified at'), blank=True, null=True)
    is_active = models.BooleanField(_('active'), default=True)
    is_staff = models.BooleanField(default=False)
    object = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'phone', 'address', 'password']

    def set_email(self, email):
        self.email = email

    def __str__(self):
        return '%s - %s %s' % (self.user_id, self.first_name, self.last_name if self.last_name is not None else '')

    def get_full_name(self):
        full_name = '%s %s' % (self.first_name, (self.last_name if self.last_name is not None else ''))
        return full_name.strip()

    def get_email(self):
        return self.email

    def short_name(self):
        return self.first_name

    def get_last_name(self):
        return self.last_name

    def getuser_id(self):
        return self.user_id

    def get_username(self):
        return self.first_name

    def get_phone(self):
        return str(self.phone)

    def get_gender(self):
        return self.gender

    def get_address(self):
        return self.address

    def email_user(self, subject, message, from_email=None, **kwargs):
        #
        # Sends an email to this User.
        #
        send_mail(subject, message, from_email, [self.email], **kwargs)

    class Meta:
        db_table = "user"
        verbose_name = "User"
        verbose_name_plural = "Users"

accounts/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib import messages
from django.conf import settings
from .models import City, Area, User
from .forms import AddUserForm
from django.contrib.auth.models import auth

from django.contrib.auth.password_validation import get_password_validators
import json
# Create your views here.

next_path = '/'


def index(request):
    addForm = AddUserForm()
    cities = City.objects.all()
    global next_path
    next_path = request.GET.get('next', '/')
    datas = {'cities': cities, 'add': addForm}
    return render(request, 'accounts/index.html', datas)


def register(request):
    cities = City.objects.all()
    if request.method == 'POST':
        form = AddUserForm(request.POST or None)
        if form.is_valid():
            print(form.errors)
            myuser = form.save()
            messages.success(request, "Registered Successfully !!")
            return redirect('login')
        else:
            for err in form.errors:
                print(err)
            return render(request, 'accounts/index.html', {'add': form, 'cities': cities})

    else:
        return render(request, 'accounts/index.html')


def login(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        user = auth.authenticate(email=email, password=password)

        if user is not None:
            auth.login(request, user)
            return redirect(next_path)
        else:
            messages.info(request, 'Invalid Credentials!!')
            return redirect('/accounts/')
    else:
        addForm = AddUserForm()
        return render(request, 'accounts/index.html', {'add': addForm})


@login_required
def logout(request):
    auth.logout(request)
    return redirect('/')


def area_handle(request):
    id = int(request.POST['id'])
    areas_list = Area.objects.filter(city_id=id)
    myList = []
    for area in areas_list:
        tup = (area.area_id, area.area_name)
        myList.append(tup)

    json_data = json.dumps(myList)
    return HttpResponse(json_data)

accounts/templates/accounts/basic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	{% load static %}
	    <link rel="stylesheet" href='{% static "accounts/css/bootstrap.css" %}'>
		<link rel="stylesheet" href='{% static "accounts/icons/css/all.css" %}'>
	    <link rel="stylesheet" href='{% static "accounts/icons/css/material-icons.min.css" %}'>
		<script src='{% static "accounts/js/jquery.js" %}'></script>
	    <script src='{% static "accounts/js/bootstrap.js" %}'></script>

    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div class="container mt-3">

    <div class="row d-flex justify-content-center align-items-center" style="background-color: #52c579;height: 6rem;border-radius: 3rem;">
        <h1 class="text-light">Reset Password</h1>
    </div>

    </div>
 {% block body %}
    {% endblock %}
</body>
</html>

accounts/templates/accounts/change_password.html
{% extends 'basic.html' %}

{% block title %} Basic-Livings : Change Password {% endblock %}

{% block body %}
{% load static %}
<section id="hero" style="padding: 30px;height: auto;background: none;">
    <div class="container d-flex justify-content-center">

        <div style="border-radius: 20px;line-height: 20px;background-color: #2154a5;box-shadow: 10px 5px 40px 5px grey;"
             class="my-4 py-4 px-5">
            <h2 class="text-center" style="color: white;">Change Password</h2>

          {% for key, error in errors.items %}

            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <strong>{{ error }}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

          {% endfor %}

            {% if form %}

            <form action="" method="post" style="color: white;">
                {% csrf_token %}

                <div class="form-group">
                    <label for="old_pwd">{{ form.old_password.label }}</label>
                    <input type="password" class="form-control" id="old_pwd" name="old_password"
                           placeholder="Enter {{ form.old_password.label }}" autofocus>
                </div>
                <div class="form-group">
                    <label for="new_pwd1">{{ form.new_password1.label }}</label>
                    <input type="password" class="form-control" id="new_pwd1" name="new_password1"
                           placeholder="Enter {{ form.new_password1.label }}">
                    <small style="color: white;">{{ form.new_password1.help_text }}</small>
                </div>
                <div class="form-group">
                    <label for="new_pwd2">{{ form.new_password2.label }}</label>
                    <input type="password" class="form-control" id="new_pwd2" name="new_password2"
                           placeholder="Enter {{ form.new_password2.label }}">

                </div>

                <button type="submit" style="border-radius: 20px;" class="btn btn-success font-weight-bold text-10">
                    Submit
                </button>
            </form>

            {% endif %}
            {% if success is not None %}
                <h2 style="color: white;">{{ success }}</h2>
            {% endif %}

        </div>
    </div>


</section><!-- End Hero -->


{% endblock %}

accounts/templates/accounts/index.html
<!DOCTYPE html5>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	{% load static %}
	    <link rel="stylesheet" href='{% static "accounts/css/bootstrap.css" %}'>
	    <link rel="stylesheet" href='{% static "accounts/css/custom.css" %}'>
		<link rel="stylesheet" href='{% static "accounts/icons/css/all.css" %}'>
	    <link rel="stylesheet" href='{% static "accounts/icons/css/material-icons.min.css" %}'>
		<script src='{% static "accounts/js/jquery.js" %}'></script>
	    <script src='{% static "accounts/js/bootstrap.js" %}'></script>

	<style>

	.errorlist {
			padding: 0px;
			text-align: left;
			color: red;
	}

@import url('https://fonts.googleapis.com/css?family=Montserrat:400,800');

    </style>
</head>
<body>
<div class="container" id="container">

	<div class="form-container p-4 sign-up-container" style="background-color: white;">
		<form action="{% url 'register' %}" method="post">

			{% for message in messages %}
			{% if message.tags == 'success' %}
			<p  class="{{ message.tags }}"style="color: green;">{{message}}</p>
			{% endif %}
			{% endfor %}
		<h1>Create Account</h1>
			{% csrf_token %}
			{% for fields in add %}
			<div class="form-group mb-0">
			{% if fields.label == 'Student' %}

			<label for="id_is_student" >Student</label>
			{% elif fields.label == 'PG Vendor' %}
			<label for="id_is_pgVendor">Paying Guest Vendor</label>
			{% elif fields.label == 'Food Vendor' %}
			<label for="id_is_foodVendor">Food Vendor</label>
			{% endif %}
			{{ fields }}
			<p style="text-align: left;color: red;">{{ fields.errors }}</p>

			</div>
			{% endfor %}
			<button type="submit">Sign Up</button>
			</form>
	</div>

	<div class="form-container sign-in-container">
		<form action="{% url 'login' %}" method="post"><br>
			<i class="fa fa-user-circle fa-6x" style="color:green"></i>
			<h1>Sign in</h1>
			<br>
			{% for error in messages %}
			{% if error.tags == 'info' %}
			<p  class="{{ error.tags }}" style="color: orange;">{{error}}</p>
			{% endif %}
			{% endfor %}
			{% csrf_token %}
			<input type="email" placeholder="Email" name="email" required oninvalid="this.setCustomValidity('Please Enter a valid Email')"/>
			<input type="password" placeholder="Password" name="password" required  oninvalid="this.setCustomValidity('Please Enter the password')" />
			<a href="{% url 'password_reset' %}">Forgot your password?</a>
			<button type="submit">Sign In</button>
			<a href="{% url 'main_home' %}">Back to Home</a>
		</form>
	</div>
	<div class="overlay-container">
		<div class="overlay">
			<div class="overlay-panel overlay-left">
				<h1>Welcome Back!</h1>
				<p>To keep connected with us please login with your personal info</p>
				<button class="ghost" id="signIn">Sign In</button>
			</div>
			<div class="overlay-panel overlay-right">
				<h1>Welcome, to BasicLivings</h1>
				<p>Enter your personal details and start journey with us</p>
				<button class="ghost" id="signUp">Sign Up</button>
			</div>
		</div>
	</div>
</div>


<!--{{ creation }}-->

<!--{{ change }}-->

<script>

    const signUpButton = document.getElementById('signUp');
const signInButton = document.getElementById('signIn');
const container = document.getElementById('container');

signUpButton.addEventListener('click', () => {
	container.classList.add("right-panel-active");
});

signInButton.addEventListener('click', () => {
	container.classList.remove("right-panel-active");
});

$('#city').on('change', function(e){
var id = $(this).val();
e.preventDefault();
$.ajax({
    url: 'area',
    type: 'POST',
    data: {id: id,
			csrfmiddlewaretoken: $("input[name=csrfmiddlewaretoken]").val()
		},

    success: function (data) {
		var areas = JSON.parse(data);
        var text;
        if(areas.length==0){
            text += `<option value="" hidden>----Not Available----</option>`;
        }else{
        text='<option value="" hidden>----Areas----</option>';
            for(i=0; i<areas.length; i++){
        	    text += `<option value='${areas[i][0]}'>${areas[i][1]}</option>`;
            }
        }
		$('#id_area_id').html(text);

		}
});
});

</script>
</body>
</html>

accounts/templates/accounts/password_reset.html
{% extends 'accounts/basic.html' %}
{% block title %}
Reset Password
{% endblock %}
{% block body %}
<div class="container mt-3">
     <h3 class="text-center" style="display: block; text-align: center">Forgot Password ?</h3>
<div class="row mt-0  d-flex justify-content-center">


    {% load static %}

    <img class="img-fluid " src='{% static "accounts/image/lock.jpeg" %}' alt="">
</div>
    <div class="row d-flex justify-content-center">
        <h5 class="w-50">Enter your email address below and we'll email you the instructions to reset the password.</h5>

    </div>
    <div class="row d-flex justify-content-center">
        <form method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit" name="send email">
        </form>
    </div>
    </div>
{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends 'accounts/basic.html' %}
{% block title %}
Password Reset Confirmation
{% endblock %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-12">
        <h3>Password reset complete</h3>
        </div>
    <div class="col-md-12">
        <p>Your password has been set. You may go ahead and log in now.</p>

        <a href="{% url 'login' %}">Log in</a>
    </div>

    </div>
</div>

{% endblock %}

accounts/templates/accounts/password_reset_form.html
{% extends 'accounts/basic.html' %}
{% block title %}
New Password
{% endblock %}
{% block body %}
<div class="container mt-4">
    <div class="row w-75 m-auto">
        <div class="col-md-12 d-flex justify-content-center">
        <h3>Enter new password</h3>
        </div>
        <div class="col-md-12 d-flex justify-content-center">
        <h5>Please enter your new password twice so we can verify you typed it in correctly.</h5>
        </div>
        <div class="col-md-12 d-flex justify-content-center">

        <form method="post">

            {% csrf_token %}
            {{form.as_p}}
            <input type="Submit" name="Update Password">

        </form>
        </div>

    </div>
</div>

{% endblock %}

accounts/templates/accounts/password_reset_sent.html
{% extends 'accounts/basic.html' %}
{% block title %}
Password Reset Link Sent
{% endblock %}
{% block body %}
<div class="container mt-4">
    <div class="row">
        <h3>Password reset sent</h3>
        <br>
        <p>We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly. If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.</p>

    </div>
</div>


{% endblock %}